### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by netrunner-exe** [MingtaoGuo/StyleSwap#3]
Hello @MingtaoGuo! I would like to know if you have any progress with model training or what stage are you at the moment? I follow your repository and it would be very interesting to see your implementation of this project! Unfortunately the authors of original paper are slow to share the models. I will be glad to feedback, best regards.

**Comment by MingtaoGuo** [comment]
> Hello @MingtaoGuo! I would like to know if you have any progress with model training or what stage are you at the moment? I follow your repository and it would be very interesting to see your implementation of this project! Unfortunately the authors of original paper are slow to share the models. I will be glad to feedback, best regards.

Hi, I'm sorry for the late reply. a few days ago, I still work for this repo, however, whatever I adjust the model, the id loss reduce very very very slowly. Even though, I use the official StyleSwap Generator architecture from the released repo by the author, it still didn't work, I feel like I'm falling apart :-<<<, and I send e-mail to the author, waiting for the response.

**Comment by netrunner-exe** [comment]
I sincerely wish you good luck in working on this project, from my own experience I will say that if something does not work out, then it is better to pause and have a good rest, and then the solution will be found by myself :) Thanks for the answer!

**Comment by MingtaoGuo** [comment]
> 

Thank you for your understanding. I will contact you when there is progress, :-D
